### ISSUE TITLE
Add ability to save to directories instead of changing filename

### ISSUE THREAD

**Issue by TxHawks** [nwtn/grunt-respimg#10]
It would be helpful if it was possible to add an option that will allow for:

````js
respimg: {
  default: {
    options: {
      widths: [
        200,
        400
      ],
    },
    files: [{
      expand: true,
      cwd: 'img/',
      src: ['*.{gif,jpg,png,svg}'],
      dest: 'img/'
    }]
  }
}
````
assuming we have `img/file.jpg`, to produce:
````bash
+--img
|
+--file.jpg
|
+--+200w/
|  |
|  +--file.jpg
|
+--+400w/
   |
   +--file.jpg
````

**Comment by nwtn** [comment]
I've been thinking about adding custom file naming anyway, so this shouldn't be too difficult to incorporate. Or I'd happily accept a PR if you feel up to it.

**Comment by TxHawks** [comment]
Never wrote any node code before, but am willing to give it a try. Is there a specific place in the code handling the naming-and-saving I could look into?

**Comment by nwtn** [comment]
Awesome! No pressure at all, but I'm stoked you're willing to give it a shot.

Check out [respimg.js line 172](https://github.com/nwtn/grunt-respimg/blob/master/tasks/respimg.js#L172). That function returns a path with the file name pattern hard-coded.

**Comment by TxHawks** [comment]
@nwtn -
I have this working, but when running the `grunt test -v`, I noticed that the task never finishes.
The output ends with:

````
Resizing images…                                                                                         
>> tmp/raster/5B-1-w320.gif is animated - skipping                                                       
>> tmp/raster/5B-1-w640.gif is animated - skipping                                                       
>> tmp/raster/5B-1-w1280.gif is animated - skipping                                                      
>> Resized image: test/assets/svg/pdf.svg resized to 320px wide, saved to tmp/svg/pdf-w320.png           
>> Resized image: test/assets/svg/pdf.svg resized to 640px wide, saved to tmp/svg/pdf-w640.png           
>> Resized image: test/assets/svg/pdf.svg resized to 1280px wide, saved to tmp/svg/pdf-w1280.png         
>> Resized image: test/assets/raster/1A-1.jpg resized to 320px wide, saved to tmp/raster/1A-1-w320.jpg   
>> Resized image: test/assets/raster/3C-2.png resized to 320px wide, saved to tmp/raster/3C-2-w320.png   
>> Resized image: test/assets/raster/3C-2.png resized to 640px wide, saved to tmp/raster/3C-2-w640.png   
>> Resized image: test/assets/raster/1A-1.jpg resized to 640px wide, saved to tmp/raster/1A-1-w640.jpg   
>> Resized image: test/assets/raster/3C-2.png resized to 1280px wide, saved to tmp/raster/3C-2-w1280.png 
````

For some reason `1A-1-w1280` does not get generated, and the task doesn't exit. 
I'm on a linux box running Ubuntu.

**Comment by nwtn** [comment]
Hm. I know my testing is messed up, so that might be the issue. Can you send a PR with what you have? I'll try merging it locally and see if I can figure out where it's breaking. Thanks!

**Comment by TxHawks** [comment]
Done

**Comment by nwtn** [comment]
Thanks! I probably won't get a chance to take a look until tomorrow or the weekend, unfortunately. :/

**Comment by TxHawks** [comment]
No worries. By the way, the test acts the same when I run it on the unmodified brunch, so it doesn't seem to be an issue with my modifications.

**Comment by nwtn** [comment]
OK cool. In that case I'll aim to fix the test and merge your changes in one shot.
