### ISSUE TITLE
Disable image optimization

### ISSUE THREAD

**Issue by leehambley** [nwtn/grunt-respimg#12]
Thanks @nwtn I'm referred here from the comment you left on the PR in svg2png. I wanted to use this *solely* for rendering svg to png in various sizes, but I'm drowning in options trying to install what seems like 15 different optimization backends... The docs mention that you can disable optimiation, but I don't see how from the options hash, I've tried a bunch of things, nothing worked

> If you plan to use image optimization with this plugin (which I recommend you do, and which is the default), you’ll probably to install the image optimizers first. With this plugin you can use image_optim, picopt, and/or ImageOptim. Unfortunately, installing them can be a bit…complicated.

That suggests there should be a way to disable them?

**Comment by nwtn** [comment]
You'd do it like this, by telling the plugin you want to run each optimizer 0 times on both the input and the output:

````
options: {
	optimize: {
		input: {
			svgo: 0,
			image_optim: 0,
			picopt: 0,
			imageOptim: 0
		},
		output: {
			svgo: 0,
			image_optim: 0,
			picopt: 0,
			imageOptim: 0
		}
	}
}
````

I'll leave this issue open as a reminder to update the documentation to make that clearer, and to maybe make turning optimization off simpler. Maybe `optimize: false`.

**Comment by leehambley** [comment]
Ah, makes sense though "pass through the optimizer `0` times"
