### ISSUE TITLE
Fatal error: Unable to locate image_optim

### ISSUE THREAD

**Issue by tomdowning82** [nwtn/grunt-respimg#16]
Im sure I have the gem image_optim installed, but when running grunt task i get the following:
Fatal error: Unable to locate image_optim

Is this something to do with my PATH not being set correctly? How do I correctly set my path if so?

**Comment by nwtn** [comment]
It sounds like it's probably a PATH thing. The grunt task looks for image_optim in a few somewhat typical places, but it wouldn't surprise me if I missed a couple possibilities. Can you run `which image_optim` in the terminal and let me know what the output is?

**Comment by lsatdown** [comment]
thanks for the quick reply! Output:
/Users/tomdowning/.rvm/gems/ruby-2.1.0/bin/image_optim

**Comment by nwtn** [comment]
Ok, that's definitely the problem. Right now the task is looking in:

* `/usr/local/sbin/image_optim`,
* `/usr/local/bin/image_optim`,
* `/usr/sbin/image_optim`,
* `/usr/bin/image_optim`,
* `/sbin/image_optim`, and
* `/bin/image_optim`

As a temporary fix, you should be able to create an alias to image_optim like this:

```bash
ln -s /Users/tomdowning/.rvm/gems/ruby-2.1.0/bin/image_optim /usr/local/bin/image_optim
```

Let me know if that works.

I'll keep this issue open until I'm able to update the plugin to solve this problem properly, without having to create any aliases.

**Comment by lsatdown** [comment]
Thanks that's got in, installed picopt and it's working. When running, it's going through 3 stages of SVGO, but then gets stuck at 1st pass of image_optim. I've left it for 10 minutes (only optimising 1 image):

```
Running "respimg:default" (respimg) task
Resizing images…
Optimizing outputs with SVGO (pass 1 of 3)…
Optimizing outputs with SVGO (pass 2 of 3)…
Optimizing outputs with SVGO (pass 3 of 3)…
Optimizing outputs with image_optim (pass 1 of 1)…
```

Lastly, how would you target multiple files within folder (recursively)?
```Eg. cwd: 'images/**/*'```

**Comment by lsatdown** [comment]
Is it possible to throw PSD files at this to convert to JPG and run through optimisation?

**Comment by nwtn** [comment]
I've created new issues for your new questions, so it's easier for others to find the answers (and easier for me to address them). Let's keep this issue focused on the image_optim PATH stuff.

**Comment by littletinyfish** [comment]
I'm getting this error in Windows. I assume something similar must be done?

In CMD when I run:
```
    where image_optim
```
I get:
```
    C:\Ruby193\Ruby193\bin\image_optim
    C:\Ruby193\Ruby193\bin\image_optim.bat
```

**Comment by nwtn** [comment]
closing because this repo is not maintained
