### ISSUE TITLE
Why rasterize SVGs?

### ISSUE THREAD

**Issue by impressivewebs** [nwtn/grunt-respimg#22]
I'm confused... Why would someone want to rasterize their SVGs to PNGs? Isn't the whole point of SVG to avoid non-scalable formats? And doesn't that go against responsiveness?

But maybe I'm not understanding what that feature is for, so I apologize in advance if this is a stupid question.

Thanks!

**Comment by kokarn** [comment]
The most common use I know for rasterizing SVGs is for IE8 fallback. That way you use the SVG for all other browsers but a resterized version of the SVG for IE8.

**Comment by impressivewebs** [comment]
Ah I see... Ok, that makes sense. I was under the impression that you were always serving the rasterized version, which obviously doesn't make a lot of sense. Ok thanks!
