### ISSUE TITLE
Disable resizing or add gravity support for cropping

### ISSUE THREAD

**Issue by macx** [nwtn/grunt-respimg#23]
As far I can see, I can't set gravitiy or aspectRatio options here. That's not bad, because I still can use [grunt-responsive-images](https://github.com/andismith/grunt-responsive-images) to do that. But I can't use `grunt-respimg` afterwards, because I can't set an option to disable the resizing of image, which is bad.

Are you planning to implement these options? I really want to use it in my projects per default, but I think, I can't.

**Comment by nwtn** [comment]
i don't really have capacity to add that feature, but it's a great idea. i'd gladly accept a pull request if you're up for it.

**Comment by nwtn** [comment]
closing because this repo is not maintained
