### ISSUE TITLE
Resizing images… Fatal error: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by fabsfabs** [nwtn/grunt-respimg#28]
Hi, I got a issue I am not able to get out.
I really want to use Resizing images in my workflow but as the title I receive always this error:

Resizing images… 
Fatal error: Cannot read property 'match' of undefined

How can I analyze the process to understand where the problem is?

Many thanks

**Comment by dualhub** [comment]
I'm also having this issue.

**Comment by nwtn** [comment]
closing because this repo is not maintained
