### ISSUE TITLE
SVGs apparently not resized

### ISSUE THREAD

**Issue by matatk** [nwtn/grunt-respimg#30]
Using `optimize: false` but otherwise the default options, it does not appear that SVGs are resized; rather they are cropped.  I tried using the SVG from this page as input: https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started

When I use `convert` on the command line (e.g. `convert -density 1200 -resize 32x32 test.svg test.png`), the image is resized as expected.  When I use this plugin, the image appears to be cropped, so only the top corner is visible in the output, rather than having it stretched.

I'm using the same Gruntfile as in #29, and I also tried `resizeFunction: resize` and `scale`, but this did not change the output.  Apologies if I'm missing anything from the docs; I have not been able to find any more options that seem relevant to what I'm trying to do.

**Comment by nwtn** [comment]
closing because this repo is not maintained
