### ISSUE TITLE
"Fatal Error: Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by whthrasher** [nwtn/grunt-respimg#31]
I keep getting this error and I am not sure how to fix it. 

Here is my code: 

'use strict';

 module.exports = function(grunt) {
  grunt.initConfig({
    respimg: {
        options: {
          widths: [200,400]
          },
        your_target: {
          files: [{
          expand:true,
          cwd: 'images_src/',
          src: ['**.{jpg,gif,png,svg,pdf}'],
          dest: 'images/'
          }]  
        },
      },
    /* Clear out the images directory if it exists */
    clean: {
      dev: {
        src: ['images'],
      },
    },

    /* Generate the images directory if it is missing */
    mkdir: {
      dev: {
        options: {
          create: ['images']
        },
      },
    },

    /* Copy the "fixed" images that don't go through processing into the images/directory */
    copy: {
      dev: {
        files: [{
          expand: true,
          src: 'images_src/fixed/*.{gif,jpg,png}',
          dest: 'images/'
        }]
      },
    },
  });
  
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-contrib-copy');
  grunt.loadNpmTasks('grunt-mkdir');
  grunt.loadNpmTasks('grunt-respimg');
  grunt.loadNpmTasks('grunt-contrib-nodeunit');
  grunt.registerTask('default',['clean', 'mkdir', 'respimg']);
};

**Comment by nwtn** [comment]
closing because this repo is not maintained
